import type { Config } from "tailwindcss";
export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}","./components/**/*.{ts,tsx}","./app/**/*.{ts,tsx}","./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center:true, padding:"clamp(1.5rem,4vw,4rem)", screens:{"2xl":"1400px"} },
    extend: {
      fontFamily: {
        display: ["Outfit","-apple-system","sans-serif"],
        serif:   ["Cormorant Garamond","Georgia","serif"],
        body:    ["Outfit","-apple-system","sans-serif"],
        sans:    ["Outfit","-apple-system","sans-serif"],
        mono:    ["SF Mono","Fira Code","ui-monospace","monospace"],
      },
      colors: {
        "hm-white":   "#FFFFFF",
        "hm-off":     "#F7F7F5",
        "hm-light":   "#EBEBEB",
        "hm-mid":     "#999999",
        "hm-dark":    "#333333",
        "hm-black":   "#000000",
        // acentos
        "hm-miro":       "#C9A87C",
        "hm-humana":     "#3B82F6",
        "hm-implantx":   "#10B981",
        "hm-scandent":   "#06B6D4",
        "hm-zerocaries": "#14B8A6",
        "hm-simetria":   "#8B5CF6",
        "hm-armonia":    "#EC4899",
        "hm-copilot":    "#84CC16",
        "hm-sentia":     "#F97316",
        // shadcn compat
        border:"hsl(var(--border))",input:"hsl(var(--input))",ring:"hsl(var(--ring))",
        background:"hsl(var(--background))",foreground:"hsl(var(--foreground))",
        primary:{DEFAULT:"hsl(var(--primary))",foreground:"hsl(var(--primary-foreground))"},
        secondary:{DEFAULT:"hsl(var(--secondary))",foreground:"hsl(var(--secondary-foreground))"},
        muted:{DEFAULT:"hsl(var(--muted))",foreground:"hsl(var(--muted-foreground))"},
        accent:{DEFAULT:"hsl(var(--accent))",foreground:"hsl(var(--accent-foreground))"},
        card:{DEFAULT:"hsl(var(--card))",foreground:"hsl(var(--card-foreground))"},
        destructive:{DEFAULT:"hsl(var(--destructive))",foreground:"hsl(var(--destructive-foreground))"},
        popover:{DEFAULT:"hsl(var(--popover))",foreground:"hsl(var(--popover-foreground))"},
      },
      borderRadius:{lg:"var(--radius)",md:"calc(var(--radius) - 2px)",sm:"calc(var(--radius) - 4px)"},
      keyframes:{
        "accordion-down":{from:{height:"0"},to:{height:"var(--radix-accordion-content-height)"}},
        "accordion-up":{from:{height:"var(--radix-accordion-content-height)"},to:{height:"0"}},
        "hm-pulse":{"0%,100%":{opacity:"1"},"50%":{opacity:"0.25"}},
        "hm-rise":{from:{opacity:"0",transform:"translateY(32px)"},to:{opacity:"1",transform:"translateY(0)"}},
      },
      animation:{
        "accordion-down":"accordion-down 0.2s ease-out",
        "accordion-up":"accordion-up 0.2s ease-out",
        "hm-pulse":"hm-pulse 2s ease infinite",
        "hm-rise":"hm-rise 0.85s cubic-bezier(.16,1,.3,1) both",
      },
    },
  },
  plugins:[require("tailwindcss-animate")],
} satisfies Config;
