import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, Loader2, ChevronLeft, ChevronRight, Lock, ArrowRight, Zap } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';

interface SimplifiedSmileSimulationProps {
  restImageUrl: string;
  smileImageUrl: string | null;
  analysisId?: string;
  autoGenerate?: boolean;
  isPremium?: boolean;
  onUpgrade?: () => void;
}

export function SimplifiedSmileSimulation({ 
  restImageUrl, 
  smileImageUrl, 
  analysisId, 
  autoGenerate = true,
  isPremium = false,
  onUpgrade
}: SimplifiedSmileSimulationProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedSmile, setGeneratedSmile] = useState<string | null>(smileImageUrl);
  const [sliderPosition, setSliderPosition] = useState(50);
  const [isDragging, setIsDragging] = useState(false);
  const [showTeaser, setShowTeaser] = useState(false);
  const [animateSlider, setAnimateSlider] = useState(true);
  const hasAutoGenerated = useRef(false);
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setGeneratedSmile(smileImageUrl);
  }, [smileImageUrl]);

  // Auto-generate smile simulation
  useEffect(() => {
    if (autoGenerate && analysisId && !smileImageUrl && !generatedSmile && !isGenerating && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      generateSmileWithAI();
    }
  }, [autoGenerate, analysisId, smileImageUrl, generatedSmile]);

  // Auto-animate slider as teaser for free users
  useEffect(() => {
    if (!generatedSmile || isPremium || !animateSlider) return;
    
    const timer = setTimeout(() => {
      // Animate slider from 80 to 20 and back to show the transformation
      const animate = async () => {
        const steps = [80, 60, 30, 15, 30, 50];
        for (const pos of steps) {
          setSliderPosition(pos);
          await new Promise(r => setTimeout(r, 400));
        }
        setAnimateSlider(false);
        // After animation, show teaser overlay for free users
        if (!isPremium) {
          setTimeout(() => setShowTeaser(true), 1000);
        }
      };
      animate();
    }, 800);
    
    return () => clearTimeout(timer);
  }, [generatedSmile, isPremium, animateSlider]);

  const generateSmileWithAI = async () => {
    if (!analysisId || isGenerating) return;
    
    setIsGenerating(true);

    try {
      const { data, error: invokeError } = await supabase.functions.invoke('generate-smile-simulation', {
        body: { analysisId, restImageUrl }
      });

      if (invokeError) throw invokeError;
      
      if (data?.smileImageUrl) {
        setGeneratedSmile(data.smileImageUrl);
      } else if (data?.error) {
        throw new Error(data.error);
      }
    } catch (err) {
      console.error('Generation error:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSliderMove = (e: React.MouseEvent | React.TouchEvent) => {
    if (!isDragging) return;
    
    const container = (containerRef.current || e.currentTarget) as HTMLElement;
    const rect = container.getBoundingClientRect();
    const clientX = 'touches' in e ? e.touches[0].clientX : e.clientX;
    const position = ((clientX - rect.left) / rect.width) * 100;
    setSliderPosition(Math.max(5, Math.min(95, position)));
  };

  // Generating state
  if (!generatedSmile) {
    return (
      <motion.div 
        className="relative rounded-3xl overflow-hidden aspect-[3/4] bg-card"
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
      >
        <img 
          src={restImageUrl} 
          alt="Tu rostro"
          className="w-full h-full object-cover"
        />
        
        <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/50 to-transparent flex flex-col items-center justify-end p-8">
          <motion.div 
            className="text-center"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
          >
            <div className="relative w-16 h-16 mx-auto mb-4">
              <Loader2 className="w-16 h-16 text-primary animate-spin" />
              <Sparkles className="w-6 h-6 text-primary absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
            </div>
            <p className="text-white font-medium text-lg">Generando tu sonrisa ideal con IA...</p>
            <p className="text-white/60 text-sm mt-1">Analizando 246 puntos biométricos</p>
            
            {/* Progress dots */}
            <div className="flex items-center justify-center gap-1.5 mt-4">
              {[0,1,2].map(i => (
                <motion.div 
                  key={i}
                  className="w-2 h-2 rounded-full bg-primary"
                  animate={{ opacity: [0.3, 1, 0.3] }}
                  transition={{ duration: 1.2, repeat: Infinity, delay: i * 0.3 }}
                />
              ))}
            </div>
          </motion.div>
        </div>
      </motion.div>
    );
  }

  // Before/After Slider with conversion hook
  return (
    <motion.div
      className="space-y-3"
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
    >
      <div 
        ref={containerRef}
        className="relative rounded-3xl overflow-hidden aspect-[3/4] cursor-ew-resize select-none"
        onMouseMove={handleSliderMove}
        onTouchMove={handleSliderMove}
        onMouseDown={() => { setIsDragging(true); setShowTeaser(false); setAnimateSlider(false); }}
        onTouchStart={() => { setIsDragging(true); setShowTeaser(false); setAnimateSlider(false); }}
        onMouseUp={() => setIsDragging(false)}
        onTouchEnd={() => setIsDragging(false)}
        onMouseLeave={() => setIsDragging(false)}
      >
        {/* Before (Rest) Image */}
        <img 
          src={restImageUrl} 
          alt="Antes"
          className="absolute inset-0 w-full h-full object-cover"
        />
        
        {/* After (Smile) Image */}
        <div 
          className="absolute inset-0 overflow-hidden"
          style={{ width: `${sliderPosition}%` }}
        >
          <img 
            src={generatedSmile} 
            alt="Después"
            className="absolute inset-0 w-full h-full object-cover"
            style={{ width: `${100 / (sliderPosition / 100)}%`, maxWidth: 'none' }}
          />
        </div>

        {/* Slider Handle */}
        <motion.div 
          className="absolute top-0 bottom-0 w-0.5 bg-white/90 shadow-xl z-10"
          style={{ left: `${sliderPosition}%`, transform: 'translateX(-50%)' }}
          animate={animateSlider ? {} : undefined}
        >
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-12 h-12 rounded-full bg-white shadow-lg flex items-center justify-center border-2 border-primary/30">
            <ChevronLeft className="w-4 h-4 text-foreground/60 -mr-1" />
            <ChevronRight className="w-4 h-4 text-foreground/60 -ml-1" />
          </div>
        </motion.div>

        {/* Labels */}
        <div className="absolute top-4 left-4 px-3 py-1.5 rounded-full bg-black/60 backdrop-blur-sm z-10">
          <span className="text-white text-xs font-medium tracking-wide uppercase">Antes</span>
        </div>
        <div className="absolute top-4 right-4 px-3 py-1.5 rounded-full bg-primary/80 backdrop-blur-sm z-10">
          <span className="text-primary-foreground text-xs font-medium flex items-center gap-1 tracking-wide uppercase">
            <Sparkles className="w-3 h-3" />
            IA Simulación
          </span>
        </div>

        {/* Free user teaser overlay */}
        <AnimatePresence>
          {showTeaser && !isPremium && (
            <motion.div 
              className="absolute inset-0 z-20 flex items-end"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              <div className="w-full bg-gradient-to-t from-black via-black/80 to-transparent p-6 pt-16">
                <div className="flex items-center gap-2 mb-2">
                  <div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center">
                    <Zap className="w-4 h-4 text-primary" />
                  </div>
                  <div>
                    <p className="text-white font-semibold text-sm">Potencial detectado</p>
                    <p className="text-primary text-xs font-medium">+15% de mejora posible</p>
                  </div>
                </div>
                <p className="text-white/70 text-xs mb-3">
                  Desbloquea tu plan de tratamiento personalizado con el Informe Premium
                </p>
                <Button 
                  size="sm" 
                  onClick={(e) => {
                    e.stopPropagation();
                    onUpgrade?.();
                  }}
                  className="w-full bg-primary hover:bg-primary/90 text-primary-foreground text-sm font-semibold gap-2"
                >
                  <Lock className="w-3.5 h-3.5" />
                  Ver Plan de Tratamiento
                  <ArrowRight className="w-3.5 h-3.5" />
                </Button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Instruction */}
      <p className="text-center text-xs text-muted-foreground">
        👆 Desliza para comparar tu antes y después con IA
      </p>
    </motion.div>
  );
}
